apiVersion: apps/v1
kind: Deployment
metadata:
  name: symply-care-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symply-care-backend
  template:
    metadata:
      labels:
        app: symply-care-backend
    spec:
      containers:
        - name: symply-care-backend
          image: ezratarab/symply_care_spring:latest
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_PASSWORD
            - name: SPRING_MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MAIL_HOST
            - name: SPRING_MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MAIL_PORT
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MAIL_USERNAME
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MAIL_PASSWORD
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_HOST
            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_PORT
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_USERNAME
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_PASSWORD
            - name: SPRING_RABBITMQ_QUEUE_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_QUEUE_NAME
            - name: SPRING_RABBITMQ_EXCHANGE_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_EXCHANGE_NAME
            - name: SPRING_RABBITMQ_ROUTING_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_ROUTING_KEY
          ports:
            - containerPort: 8080
