apiVersion: apps/v1
kind: Deployment
metadata:
  name: symply-care-backend-deployment
  labels:
    app: symply-care-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: symply-care-backend
  template:
    metadata:
      labels:
        app: symply-care-backend
    spec:
      containers:
      - name: symply-care-backend-container
        image: ezratarab/symply_care_spring:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DATABASE_URL
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DATABASE_PASSWORD
        - name: MAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MAIL_USERNAME
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MAIL_PASSWORD
        - name: RABBITMQ_HOST
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBITMQ_PORT
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBITMQ_USERNAME
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBITMQ_PASSWORD
        - name: RABBITMQ_QUEUE_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBITMQ_QUEUE_NAME
        - name: RABBITMQ_EXCHANGE_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBITMQ_EXCHANGE_NAME
        - name: RABBITMQ_ROUTING_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBITMQ_ROUTING_KEY
