apiVersion: v1
kind: Service
metadata:
  name: symply-care-backend-service
spec:
  selector:
    app: symply-care-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
