name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Set up JDK 17 for Maven build
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    # Build the Maven project
    - name: Build with Maven
      run: mvn clean package
      
    # Archive the JAR file as an artifact
    - name: Archive JAR
      uses: actions/upload-artifact@v3
      with:
        name: symply-care-backend
        path: target/*.jar
    
    # Build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
